chore: Fix clippy lint by Rust 1.98 (#822)
<!-- Close or Related Issues -->

先週リリースされた Rust 1.98 から以下が clippy のルールに加わりました。`cargo clippy --fix`
だけで修正できます。

```
    Checking nusamai-citygml v0.1.19 (/home/runner/work/plateau-gis-converter/plateau-gis-converter/nusamai-citygml)
error: using `chunks_exact` with a constant chunk size
   --> nusamai-citygml/src/parser.rs:930:26
    |
930 |                         .chunks_exact(3)
    |                          ^^^^^^^^^^^^^^^ help: consider using `as_chunks` instead: `as_chunks::<3>().0.iter()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.98.0/index.html#chunks_exact_to_as_chunks
    = note: `-D clippy::chunks-exact-to-as-chunks` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::chunks_exact_to_as_chunks)]`

error: could not compile `nusamai-citygml` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

### What I did
<!-- Please describe the motivation behind this PR and the changes it
introduces. -->


### Notes
<!-- If manual testing is required, please describe the procedure. -->