CLIのビルドをアプリケーションと統合 (#774)
<!-- Close or Related Issues -->
Close #0

### What I did
<!-- Please describe the motivation behind this PR and the changes it
introduces. -->

- アップロードに頻繁に失敗するため、競合しないようにCIを統合

```
Run softprops/action-gh-release@v2
  with:
    files: nusamai-*.tar.gz
    overwrite_files: true
    token: ***
Found release v0.1.11 (with id=283369272)
♻️ Deleting previously uploaded asset nusamai-v0.1.11-x86_64-unknown-linux-gnu.tar.gz...
♻️ Deleting previously uploaded asset nusamai-v0.1.11-aarch64-apple-darwin.tar.gz...
⬆️ Uploading nusamai-v0.1.11-x86_64-unknown-linux-gnu.tar.gz...
⬆️ Uploading nusamai-v0.1.11-aarch64-apple-darwin.tar.gz...
✅ Uploaded nusamai-v0.1.11-x86_64-unknown-linux-gnu.tar.gz
✅ Uploaded nusamai-v0.1.11-aarch64-apple-darwin.tar.gz
Finalizing release...
retrying... (2 retries remaining)
retrying... (1 retries remaining)
retrying... (0 retries remaining)
❌ Too many retries. Aborting...
Error: Too many retries.
```

### Notes
<!-- If manual testing is required, please describe the procedure. -->